import Link from "next/link";
import { ButtonLink, PageShell, ProjectMark, SectionLabel } from "@/components/site";
import { AnimatedArrow, MotionItem, MotionSection } from "@/components/motion";
import { projects } from "@/data/projects";

export default function WorkPage() {
  return <PageShell>
    <section className="bg-dark text-light"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:px-16 lg:py-16"><SectionLabel>Selected work</SectionLabel><h1 className="display mt-6 max-w-4xl text-[clamp(3.1rem,6vw,6rem)] leading-[.92]">Real systems,<br /><span className="text-cyan">practical outcomes.</span></h1><p className="mt-7 max-w-2xl text-lg leading-relaxed text-muted-dark">A proof index of systems built for websites, publishing workflows, AI automation, and operational clarity.</p></div></section>
    <section className="bg-light text-ink"><MotionSection className="mx-auto max-w-7xl px-6 py-12 sm:px-10 lg:px-16">{projects.map((project) => <MotionItem key={project.slug}><article id={project.slug} className="group grid gap-5 border-b border-light-line py-7 transition-colors hover:bg-ink/[.02] lg:grid-cols-[72px_1fr_1.1fr_90px] lg:items-start"><span className="font-mono text-xs text-muted-light">{project.index}</span><div><ProjectMark slug={project.slug} /><h2 className="display mt-3 text-3xl transition-colors group-hover:text-blue sm:text-4xl">{project.name}</h2><p className="mt-2 text-sm text-muted-light">{project.category}</p></div><div><p className="text-base leading-relaxed text-muted-light">{project.description}</p><p className="mt-3 text-sm leading-relaxed"><span className="font-semibold text-ink">What this proves: </span>{project.proof}</p></div><div className="lg:text-right">{project.link ? <a href={project.link} target="_blank" rel="noreferrer" className="font-mono text-sm tracking-[.02em] text-blue hover:underline">Open <AnimatedArrow /></a> : <Link href={project.href} className="font-mono text-sm tracking-[.02em] text-blue hover:underline">Read case study <AnimatedArrow /></Link>}</div></article></MotionItem>)}</MotionSection></section>
    <section className="bg-blue text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-16 sm:px-10 lg:flex-row lg:items-end lg:justify-between lg:px-16"><MotionItem><h2 className="display max-w-3xl text-[clamp(2.8rem,5vw,5rem)]">Need a system that keeps working?</h2></MotionItem><MotionItem><ButtonLink href="/about" light>Book an audit</ButtonLink></MotionItem></div></section>
  </PageShell>;
}
