import type { Metadata } from "next";
import { ButtonLink, PageShell, SectionLabel } from "@/components/site";
import { MotionItem, MotionSection } from "@/components/motion";
import { MaskedHeadline, MaskedLine, WordReveal } from "@/components/motion";
import { projects } from "@/data/projects";
import { createMetadata } from "@/src/lib/seo";

export const metadata: Metadata = createMetadata({ path: "/about", title: "About", description: "Vijay Kumaran builds practical websites, business systems, and AI automations that reduce manual work and run reliably every day." });

const stack = ["Next.js", "TypeScript", "Tailwind CSS", "Cloudflare", "D1/R2", "Durable Objects", "Postgres", "pgvector", "AI Workflows", "GitHub"];
const approach = [["01", "Clarity first", "I start by understanding the real problem, goals, and constraints. Simple scope. Clear outcomes."], ["02", "Reliable systems", "I build systems that are secure, tested, and designed to handle real-world usage."], ["03", "Traceable automation", "Automations should be observable and accountable. I design workflows that are transparent and easy to trust."], ["04", "Maintainable delivery", "Clean code, documentation, and thoughtful handover so the system can keep working after launch."]];
const recentProof = projects.map((p) => [p.name, p.metric]);

export default function AboutPage() {
  return <PageShell>
    <section className="bg-dark text-light"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-14 sm:px-10 lg:grid-cols-[1.2fr_.8fr] lg:gap-16 lg:px-16 lg:py-16"><div><SectionLabel>About</SectionLabel><MaskedHeadline className="display mt-6 max-w-5xl text-[clamp(3.1rem,6vw,6rem)] leading-[.92]"><MaskedLine>Vijay Kumaran</MaskedLine></MaskedHeadline><WordReveal text="AI Automation & Web Systems Consultant" className="mt-6 text-2xl text-cyan sm:text-3xl" /><p className="mt-7 max-w-2xl text-lg leading-relaxed text-muted-dark">I build practical websites, business systems, and AI automations that reduce manual work and run reliably every day.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="mailto:element.bendr@gmail.com" light>Start a conversation</ButtonLink><ButtonLink href="/work" secondary>View work</ButtonLink></div><p className="mt-8 max-w-3xl border-t border-dark-line pt-4 text-sm leading-relaxed text-muted-dark">Recent work spans Cloudflare-native AI agents, AI memory systems, institutional publishing workflows, and production brand websites.</p></div><MotionItem className="self-end"><aside className="border-y border-dark-line py-5"><SectionLabel>Recent proof</SectionLabel><ul className="mt-5 divide-y divide-dark-line">{recentProof.map(([name, proof]) => <li className="flex items-baseline justify-between gap-4 py-3" key={name}><span className="font-mono text-sm text-light">{name}</span><span className="text-right text-sm leading-relaxed text-muted-dark">{proof}</span></li>)}</ul></aside></MotionItem></div></section>
    <section id="approach" className="bg-light text-ink"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:px-16"><SectionLabel light>How I work</SectionLabel><div className="mt-8 divide-y divide-light-line">{approach.map(([num, title, copy]) => <div className="grid gap-4 py-6 lg:grid-cols-[72px_1fr_1fr]" key={num}><span className="font-mono text-xs text-muted-light">{num}</span><h2 className="display text-3xl">{title}</h2><p className="max-w-md text-base leading-relaxed text-muted-light">{copy}</p></div>)}</div></div></section>
    <section id="audit" className="bg-dark text-light"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:grid lg:grid-cols-[1fr_1fr] lg:gap-16 lg:px-16 lg:py-16"><div><SectionLabel>Book an audit</SectionLabel><h2 className="display mt-6 text-[clamp(2.8rem,5vw,5rem)]">Your systems<br /><span className="text-cyan">under the lens.</span></h2><p className="mt-7 max-w-xl text-lg leading-relaxed text-muted-dark">A focused review of your current website, business system, or automation workflow. You get a written assessment with clear next steps.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="mailto:element.bendr@gmail.com" light>Start an audit conversation</ButtonLink><ButtonLink href="/work" secondary>View case studies</ButtonLink></div></div><div className="mt-10 space-y-6 lg:mt-0"><div className="border border-dark-line p-5"><p className="font-mono text-xs text-cyan">01 — Scope</p><p className="mt-3 text-base leading-relaxed text-muted-dark">We define the system, the goals, and what success looks like. 30-minute call or async brief.</p></div><div className="border border-dark-line p-5"><p className="font-mono text-xs text-cyan">02 — Assessment</p><p className="mt-3 text-base leading-relaxed text-muted-dark">I review the architecture, workflows, performance, and automation gaps. You get a written report.</p></div><div className="border border-dark-line p-5"><p className="font-mono text-xs text-cyan">03 — Recommendations</p><p className="mt-3 text-base leading-relaxed text-muted-dark">Prioritized action items: what to fix, what to build, what to automate. No fluff, no upsell.</p></div><div className="border border-dark-line p-5"><p className="font-mono text-xs text-cyan">04 — Build (optional)</p><p className="mt-3 text-base leading-relaxed text-muted-dark">If you want me to implement the recommendations, we scope the build as a separate project.</p></div></div></div></section>
    <section className="bg-dark-soft text-light"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:px-16"><SectionLabel>Working stack</SectionLabel><h2 className="display mt-6 text-[clamp(2.8rem,5vw,5rem)]">Modern, fast,<br /><span className="text-cyan">secure.</span></h2><MotionSection className="mt-8 flex flex-wrap gap-2">{stack.map((item) => <MotionItem key={item}><span className="border border-dark-line px-4 py-3 font-mono text-xs text-muted-dark">{item}</span></MotionItem>)}</MotionSection></div></section>
    <section id="contact" className="bg-blue text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-14 sm:px-10 lg:flex-row lg:items-end lg:justify-between lg:px-16"><div><SectionLabel>Contact</SectionLabel><h2 className="display mt-6 text-[clamp(3.1rem,6vw,6rem)] leading-[.9]">Start a<br />conversation.</h2><a href="mailto:element.bendr@gmail.com" className="mt-6 inline-block text-lg underline underline-offset-4">element.bendr@gmail.com</a></div><ButtonLink href="mailto:element.bendr@gmail.com" light>Send an email</ButtonLink></div></section>
  </PageShell>;
}
