import { ButtonLink, PageShell, SectionLabel } from "@/components/site";
import { MotionItem, MotionSection } from "@/components/motion";

const stack = ["Next.js", "TypeScript", "Tailwind CSS", "Cloudflare", "D1/R2", "Durable Objects", "Postgres", "pgvector", "AI Workflows", "GitHub"];
const approach = [["01", "Clarity first", "I start by understanding the real problem, goals, and constraints. Simple scope. Clear outcomes."], ["02", "Reliable systems", "I build systems that are secure, tested, and designed to handle real-world usage."], ["03", "Traceable automation", "Automations should be observable and accountable. I design workflows that are transparent and easy to trust."], ["04", "Maintainable delivery", "Clean code, documentation, and thoughtful handover so the system can keep working after launch."]];
const recentProof = [["newsharness", "Cloudflare-native intelligence system"], ["memory-os", "AI coding-agent memory system"], ["KPDC / Trifecta", "Institutional publishing workflow"], ["SteelMade", "Production brand website"]];

export default function AboutPage() {
  return <PageShell>
    <section className="bg-dark text-light"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-14 sm:px-10 lg:grid-cols-[1.2fr_.8fr] lg:gap-16 lg:px-16 lg:py-16"><div><SectionLabel>About</SectionLabel><h1 className="display mt-6 max-w-5xl text-[clamp(3.1rem,6vw,6rem)] leading-[.92]">Vijay Kumaran</h1><p className="mt-6 text-2xl text-cyan sm:text-3xl">AI Automation &amp; Web Systems Consultant</p><p className="mt-7 max-w-2xl text-lg leading-relaxed text-muted-dark">I build practical websites, business systems, and AI automations that reduce manual work and run reliably every day.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="mailto:element.bendr@gmail.com" light>Start a conversation</ButtonLink><ButtonLink href="/work" secondary>View work</ButtonLink></div><p className="mt-8 max-w-3xl border-t border-dark-line pt-4 text-sm leading-relaxed text-muted-dark">Recent work spans Cloudflare-native AI agents, AI memory systems, institutional publishing workflows, and production brand websites.</p></div><MotionItem className="self-end"><aside className="border-y border-dark-line py-5"><SectionLabel>Recent proof</SectionLabel><ul className="mt-5 divide-y divide-dark-line">{recentProof.map(([name, proof]) => <li className="flex items-baseline justify-between gap-4 py-3" key={name}><span className="font-mono text-sm text-light">{name}</span><span className="text-right text-sm leading-relaxed text-muted-dark">{proof}</span></li>)}</ul></aside></MotionItem></div></section>
    <section id="approach" className="bg-light text-ink"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:px-16"><SectionLabel light>How I work</SectionLabel><div className="mt-8 divide-y divide-light-line">{approach.map(([num, title, copy]) => <div className="grid gap-4 py-6 lg:grid-cols-[72px_1fr_1fr]" key={num}><span className="font-mono text-xs text-muted-light">{num}</span><h2 className="display text-3xl">{title}</h2><p className="max-w-md text-base leading-relaxed text-muted-light">{copy}</p></div>)}</div></div></section>
    <section className="bg-dark-soft text-light"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:px-16"><SectionLabel>Working stack</SectionLabel><h2 className="display mt-6 text-[clamp(2.8rem,5vw,5rem)]">Modern, fast,<br /><span className="text-cyan">secure.</span></h2><MotionSection className="mt-8 flex flex-wrap gap-2">{stack.map((item) => <MotionItem key={item}><span className="border border-dark-line px-4 py-3 font-mono text-xs text-muted-dark">{item}</span></MotionItem>)}</MotionSection></div></section>
    <section id="contact" className="bg-blue text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-14 sm:px-10 lg:flex-row lg:items-end lg:justify-between lg:px-16"><div><SectionLabel>Contact</SectionLabel><h2 className="display mt-6 text-[clamp(3.1rem,6vw,6rem)] leading-[.9]">Start a<br />conversation.</h2><a href="mailto:element.bendr@gmail.com" className="mt-6 inline-block text-lg underline underline-offset-4">element.bendr@gmail.com</a></div><ButtonLink href="mailto:element.bendr@gmail.com" light>Send an email</ButtonLink></div></section>
  </PageShell>;
}
