import type { Metadata } from "next";
import { ButtonLink, PageShell, SectionLabel } from "@/components/site";
import { TrackVisit } from "@/components/TrackVisit";
import { MotionItem, MotionSection } from "@/components/motion";
import { CaseStudyMeta } from "@/components/CaseStudyMeta";

export const metadata: Metadata = {
  title: "ArtSports Content OS — Structured Content Automation",
  description: "A structured content planning and caption-generation workflow with deterministic planning, bounded LLM captions, and human review.",
};

const chips = ["YAML schemas", "LLM captions", "Validation", "Retries", "Daily briefs"];
const capabilities = ["Deterministic calendar planning", "Prompt compilation", "Bounded LLM captions", "Deterministic fallbacks", "Validation and retries", "Operator-friendly daily briefs"];

export default function ArtSportsPage() {
  return <PageShell><TrackVisit slug="artsports-content-os" />
    <section className="bg-dark text-light"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:px-16 lg:py-16"><SectionLabel>Case study / 06</SectionLabel><h1 className="display mt-6 max-w-5xl text-[clamp(2.95rem,5.7vw,5.75rem)] leading-[.92]">Structured Content<br /><span className="text-cyan">Automation</span></h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-muted-dark">A structured content planning and caption-generation workflow for consistent, reviewable publishing.</p><CaseStudyMeta slug="artsports-content-os" /><div className="mt-7 grid gap-px border border-dark-line bg-dark-line sm:grid-cols-2 lg:grid-cols-4">{[["Type", "Content operations"], ["Platform", "Workflow system"], ["Status", "Built content workflow"], ["Stack", "YAML · LLM captions · Validation"]].map(([label, value]) => <div className="bg-dark p-4" key={label}><p className="font-mono text-[10px] uppercase tracking-[.12em] text-muted-dark">{label}</p><p className="mt-2 text-sm text-light">{value}</p></div>)}</div><div className="mt-7 flex flex-wrap gap-2">{chips.map((chip) => <span key={chip} className="border border-dark-line px-3 py-2 font-mono text-[11px] text-muted-dark">{chip}</span>)}</div></div></section>
    <section className="bg-light text-ink"><div className="mx-auto max-w-7xl px-6 py-12 sm:px-10 lg:px-16"><MotionSection className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><SectionLabel light>Overview</SectionLabel><p className="mt-6 text-2xl leading-tight">Manual content planning creates inconsistent output, missed schedules, and weak review control.</p></div><p className="max-w-xl text-base leading-relaxed text-muted-light">ArtSports Content OS plans content on a deterministic calendar, compiles prompts from YAML schemas, and generates bounded LLM captions with fallbacks, validation, and retries.</p></MotionSection><MotionSection className="mt-10 border-y border-light-line py-7"><SectionLabel light>System architecture</SectionLabel><div className="mt-5 grid gap-px overflow-hidden border border-light-line bg-light-line sm:grid-cols-3 lg:grid-cols-6">{[["Plan", "Calendar planning"], ["Schema", "YAML structures"], ["Generate", "Bounded LLM captions"], ["Validate", "Checks + retries"], ["Fallback", "Deterministic output"], ["Brief", "Daily operator brief"]].map(([step, tool], i) => <div key={step} className="bg-light p-4"><span className="font-mono text-xs text-blue">0{i + 1}</span><p className="mt-5 text-sm font-semibold leading-tight">{step}</p><p className="mt-1 text-xs leading-relaxed text-muted-light">{tool}</p></div>)}</div></MotionSection><MotionSection className="grid gap-10 py-12 lg:grid-cols-2"><div><SectionLabel light>Problem</SectionLabel><p className="mt-6 text-2xl leading-tight">Content teams need consistency and review control without manual copywriting every day.</p></div><div><SectionLabel light>What it does</SectionLabel><ul className="mt-5 divide-y divide-light-line">{capabilities.map((item) => <li key={item} className="py-2.5 text-base text-muted-light">{item}</li>)}</ul></div></MotionSection><MotionSection className="grid gap-10 border-t border-light-line py-12 lg:grid-cols-2"><div><SectionLabel light>What this proves</SectionLabel><ul className="mt-6 space-y-3 text-base leading-relaxed"><li>AI-assisted content operations that stay human-reviewable.</li><li>Structured planning before generation.</li><li>Deterministic generation discipline and fallbacks.</li><li>Operator-friendly briefs instead of raw outputs.</li></ul></div><div><SectionLabel light>Note</SectionLabel><p className="mt-6 text-base text-muted-light">The repository is private. This public case study is sanitized; source and client material are not published.</p></div></MotionSection></div></section>
    <section className="bg-blue text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-14 sm:px-10 lg:flex-row lg:items-end lg:justify-between lg:px-16"><MotionItem><h2 className="display max-w-3xl text-[clamp(2.8rem,5vw,5rem)]">Need content that writes itself — reviewably?</h2></MotionItem><MotionItem><ButtonLink href="/about#audit" light>Book an audit</ButtonLink></MotionItem></div></section>
  </PageShell>;
}
