import type { Metadata } from "next";
import { ButtonLink, PageShell, SectionLabel } from "@/components/site";
import { TrackVisit } from "@/components/TrackVisit";
import { MotionItem, MotionSection } from "@/components/motion";
import { CaseStudyMeta } from "@/components/CaseStudyMeta";
import { createMetadata } from "@/src/lib/seo";

export const metadata: Metadata = createMetadata({ path: "/work/memory-os", title: "memory-os — AI Coding-Agent Memory System", description: "A governed memory operating system for AI coding agents: Git-reviewed Markdown, GBrain retrieval, Postgres/pgvector, and verification-gated handoffs." });

const chips = ["Git-reviewed Markdown", "GBrain", "Postgres/pgvector", "Beads task state", "Agent skills", "Verification-gated handoffs"];
const capabilities = ["Durable project knowledge", "Evidence / date / source / owner rules", "Setup / verify / sync workflows", "Backup / restore workflows", "Verification-gated handoffs"];

export default function MemoryOsPage() {
  return <PageShell><TrackVisit slug="memory-os" />
    <section className="bg-dark text-light"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:px-16 lg:py-16"><SectionLabel>Case study / 02</SectionLabel><h1 className="display mt-6 max-w-5xl text-[clamp(2.95rem,5.7vw,5.75rem)] leading-[.92]">AI Coding-Agent<br /><span className="text-cyan">Memory System</span></h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-muted-dark">A governed memory operating system for AI coding agents: durable project knowledge, task state, retrieval, and evidence-based handoffs.</p><CaseStudyMeta slug="memory-os" /><div className="mt-7 grid gap-px border border-dark-line bg-dark-line sm:grid-cols-2 lg:grid-cols-4">{[["Type", "AI memory system"], ["Canonical truth", "Git-reviewed Markdown"], ["Status", "Built internal system"], ["Stack", "GBrain · Postgres/pgvector · Beads"]].map(([label, value]) => <div className="bg-dark p-4" key={label}><p className="font-mono text-[10px] uppercase tracking-[.12em] text-muted-dark">{label}</p><p className="mt-2 text-sm text-light">{value}</p></div>)}</div><div className="mt-7 flex flex-wrap gap-2">{chips.map((chip) => <span key={chip} className="border border-dark-line px-3 py-2 font-mono text-[11px] text-muted-dark">{chip}</span>)}</div></div></section>
    <section className="bg-light text-ink"><div className="mx-auto max-w-7xl px-6 py-12 sm:px-10 lg:px-16"><MotionSection className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><SectionLabel light>Overview</SectionLabel><p className="mt-6 text-2xl leading-tight">AI coding agents lose context, repeat mistakes, and mix temporary task state with durable knowledge.</p></div><p className="max-w-xl text-base leading-relaxed text-muted-light">memory-os solves that with a governed system where agents keep durable project knowledge separate from in-flight task state, backed by retrieval and evidence rules.</p></MotionSection><MotionSection className="mt-10 border-y border-light-line py-7"><SectionLabel light>System architecture</SectionLabel><div className="mt-5 grid gap-px overflow-hidden border border-light-line bg-light-line sm:grid-cols-3 lg:grid-cols-6">{[["Knowledge", "Git-reviewed Markdown"], ["Retrieval", "GBrain"], ["Projection", "Postgres/pgvector"], ["Task state", "Beads"], ["Skills", "Agent skills"], ["Handoff", "Verification-gated"]].map(([step, tool], i) => <div key={step} className="bg-light p-4"><span className="font-mono text-xs text-blue">0{i + 1}</span><p className="mt-5 text-sm font-semibold leading-tight">{step}</p><p className="mt-1 text-xs leading-relaxed text-muted-light">{tool}</p></div>)}</div></MotionSection><MotionSection className="grid gap-10 py-12 lg:grid-cols-2"><div><SectionLabel light>Problem</SectionLabel><p className="mt-6 text-2xl leading-tight">Coding agents drift: context is lost between sessions, mistakes repeat, and temporary state pollutes durable knowledge.</p></div><div><SectionLabel light>What it does</SectionLabel><ul className="mt-5 divide-y divide-light-line">{capabilities.map((item) => <li key={item} className="py-2.5 text-base text-muted-light">{item}</li>)}</ul></div></MotionSection><MotionSection className="grid gap-10 border-t border-light-line py-12 lg:grid-cols-2"><div><SectionLabel light>What this proves</SectionLabel><ul className="mt-6 space-y-3 text-base leading-relaxed"><li>AI-assisted engineering operations at scale.</li><li>Memory governance for coding agents.</li><li>Postgres/pgvector usage for retrieval.</li><li>Agent workflow architecture and evidence-based automation discipline.</li></ul></div><div><SectionLabel light>Stack</SectionLabel><ul className="mt-6 space-y-3 text-base text-muted-light"><li>Git-reviewed Markdown as canonical truth</li><li>GBrain retrieval</li><li>Postgres / pgvector projections</li><li>Beads task state and agent skills</li></ul></div></MotionSection></div></section>
    <section className="bg-blue text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-14 sm:px-10 lg:flex-row lg:items-end lg:justify-between lg:px-16"><MotionItem><h2 className="display max-w-3xl text-[clamp(2.8rem,5vw,5rem)]">Want to build a system that remembers?</h2></MotionItem><MotionItem><ButtonLink href="/about#audit" light>Book an audit</ButtonLink></MotionItem></div></section>
  </PageShell>;
}
