import type { Metadata } from "next";
import { ButtonLink, PageShell, SectionLabel } from "@/components/site";
import { TrackVisit } from "@/components/TrackVisit";
import { MotionItem, MotionSection } from "@/components/motion";

export const metadata: Metadata = {
  title: "ChronoQuill — WhatsApp Publishing Automation",
  description: "A local-first WhatsApp publishing automation service with deterministic scheduling, duplicate prevention, and reviewable operations.",
};

const chips = ["Node.js", "TypeScript", "SQLite", "Baileys", "systemd", "CLI"];
const capabilities = ["Deterministic quote ingestion", "Scheduled publishing", "Duplicate prevention", "Missed-send recovery", "Inbound reply capture", "Reviewable operations"];

export default function ChronoQuillPage() {
  return <PageShell><TrackVisit slug="chronoquill" />
    <section className="bg-dark text-light"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:px-16 lg:py-16"><SectionLabel>Case study / 05</SectionLabel><h1 className="display mt-6 max-w-5xl text-[clamp(2.95rem,5.7vw,5.75rem)] leading-[.92]">WhatsApp Publishing<br /><span className="text-cyan">Automation</span></h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-muted-dark">A local-first automation service for repeatable, reviewable WhatsApp content delivery.</p><div className="mt-7 grid gap-px border border-dark-line bg-dark-line sm:grid-cols-2 lg:grid-cols-4">{[["Type", "Publishing automation"], ["Platform", "Local-first service"], ["Status", "Built local automation"], ["Stack", "Node.js · TypeScript · SQLite · Baileys"]].map(([label, value]) => <div className="bg-dark p-4" key={label}><p className="font-mono text-[10px] uppercase tracking-[.12em] text-muted-dark">{label}</p><p className="mt-2 text-sm text-light">{value}</p></div>)}</div><div className="mt-7 flex flex-wrap gap-2">{chips.map((chip) => <span key={chip} className="border border-dark-line px-3 py-2 font-mono text-[11px] text-muted-dark">{chip}</span>)}</div></div></section>
    <section className="bg-light text-ink"><div className="mx-auto max-w-7xl px-6 py-12 sm:px-10 lg:px-16"><MotionSection className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><SectionLabel light>Overview</SectionLabel><p className="mt-6 text-2xl leading-tight">Recurring WhatsApp publishing needs predictable scheduling, duplicate prevention, and recovery — not manual sends.</p></div><p className="max-w-xl text-base leading-relaxed text-muted-light">ChronoQuill runs local-first: deterministic quote ingestion and scheduled delivery with persistent auth, inbound reply capture, and systemd-managed operation.</p></MotionSection><MotionSection className="mt-10 border-y border-light-line py-7"><SectionLabel light>System architecture</SectionLabel><div className="mt-5 grid gap-px overflow-hidden border border-light-line bg-light-line sm:grid-cols-3 lg:grid-cols-6">{[["Ingest", "Deterministic quotes"], ["Schedule", "Predictable publishing"], ["Transport", "Baileys"], ["State", "SQLite"], ["Ops", "CLI + systemd"], ["Recovery", "Missed-send retry"]].map(([step, tool], i) => <div key={step} className="bg-light p-4"><span className="font-mono text-xs text-blue">0{i + 1}</span><p className="mt-5 text-sm font-semibold leading-tight">{step}</p><p className="mt-1 text-xs leading-relaxed text-muted-light">{tool}</p></div>)}</div></MotionSection><MotionSection className="grid gap-10 py-12 lg:grid-cols-2"><div><SectionLabel light>Problem</SectionLabel><p className="mt-6 text-2xl leading-tight">Manual WhatsApp publishing is unpredictable, error-prone, and unverifiable.</p></div><div><SectionLabel light>What it does</SectionLabel><ul className="mt-5 divide-y divide-light-line">{capabilities.map((item) => <li key={item} className="py-2.5 text-base text-muted-light">{item}</li>)}</ul></div></MotionSection><MotionSection className="grid gap-10 border-t border-light-line py-12 lg:grid-cols-2"><div><SectionLabel light>What this proves</SectionLabel><ul className="mt-6 space-y-3 text-base leading-relaxed"><li>Workflow automation with deterministic scheduling.</li><li>Operational tooling for a real messaging channel.</li><li>CLI and service design discipline.</li><li>Local-first automation that runs without a cloud dependency.</li></ul></div><div><SectionLabel light>Code</SectionLabel><ul className="mt-6 space-y-3 text-base text-muted-light"><li><a href="https://github.com/element-bendr/chronoquill" target="_blank" rel="noreferrer" className="text-blue hover:underline">Public implementation ↗</a></li></ul></div></MotionSection></div></section>
    <section className="bg-blue text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-14 sm:px-10 lg:flex-row lg:items-end lg:justify-between lg:px-16"><MotionItem><h2 className="display max-w-3xl text-[clamp(2.8rem,5vw,5rem)]">Need publishing that never misses a send?</h2></MotionItem><MotionItem><ButtonLink href="/about" light>Book an audit</ButtonLink></MotionItem></div></section>
  </PageShell>;
}
