import type { Metadata } from "next";
import { ButtonLink, PageShell, SectionLabel } from "@/components/site";
import { TrackVisit } from "@/components/TrackVisit";
import { MotionItem, MotionSection } from "@/components/motion";
import { CaseStudyMeta } from "@/components/CaseStudyMeta";
import { createMetadata } from "@/src/lib/seo";

export const metadata: Metadata = createMetadata({ path: "/work/steelmade", title: "SteelMade — Production Furniture Brand Website", description: "A production furniture brand website focused on product/category discovery, brand presentation, and enquiry generation." });

const chips = ["Next.js", "TypeScript", "Cloudinary", "Netlify", "Cloudflare"];
const capabilities = ["Product and category discovery", "Brand presentation", "Responsive layout", "Quote / enquiry-focused flows"];

export default function SteelMadePage() {
  return <PageShell><TrackVisit slug="steelmade" />
    <section className="bg-dark text-light"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:px-16 lg:py-16"><SectionLabel>Case study / 04</SectionLabel><h1 className="display mt-6 max-w-5xl text-[clamp(2.95rem,5.7vw,5.75rem)] leading-[.92]">Production Furniture<br /><span className="text-cyan">Brand Website</span></h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-muted-dark">A production furniture brand website built around product and category discovery, brand presentation, and enquiry generation.</p><CaseStudyMeta slug="steelmade" /><div className="mt-7 grid gap-px border border-dark-line bg-dark-line sm:grid-cols-2 lg:grid-cols-4">{[["Type", "Brand website"], ["Platform", "Next.js web"], ["Status", "Production client website"], ["Stack", "Next.js · Cloudinary · Netlify · Cloudflare"]].map(([label, value]) => <div className="bg-dark p-4" key={label}><p className="font-mono text-[10px] uppercase tracking-[.12em] text-muted-dark">{label}</p><p className="mt-2 text-sm text-light">{value}</p></div>)}</div><div className="mt-7 flex flex-wrap gap-2">{chips.map((chip) => <span key={chip} className="border border-dark-line px-3 py-2 font-mono text-[11px] text-muted-dark">{chip}</span>)}</div></div></section>
    <section className="bg-light text-ink"><div className="mx-auto max-w-7xl px-6 py-12 sm:px-10 lg:px-16"><MotionSection className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><SectionLabel light>Overview</SectionLabel><p className="mt-6 text-2xl leading-tight">A furniture and manufacturing brand needed a professional web presence with clear product paths and enquiry routes.</p></div><p className="max-w-xl text-base leading-relaxed text-muted-light">SteelMade is a media-heavy production website: responsive brand presentation, product and category navigation, and quote-oriented flows that turn visitors into enquiries.</p></MotionSection><MotionSection className="mt-10 border-y border-light-line py-7"><SectionLabel light>System architecture</SectionLabel><div className="mt-5 grid gap-px overflow-hidden border border-light-line bg-light-line sm:grid-cols-3 lg:grid-cols-6">{[["Presentation", "Responsive brand layout"], ["Media", "Cloudinary"], ["Product", "Category + product navigation"], ["Conversion", "Enquiry flows"], ["Deployment", "Netlify + Cloudflare"], ["Delivery", "Production client site"]].map(([step, tool], i) => <div key={step} className="bg-light p-4"><span className="font-mono text-xs text-blue">0{i + 1}</span><p className="mt-5 text-sm font-semibold leading-tight">{step}</p><p className="mt-1 text-xs leading-relaxed text-muted-light">{tool}</p></div>)}</div></MotionSection><MotionSection className="grid gap-10 py-12 lg:grid-cols-2"><div><SectionLabel light>Problem</SectionLabel><p className="mt-6 text-2xl leading-tight">The brand had no web presence that presented products well or captured enquiries.</p></div><div><SectionLabel light>What it does</SectionLabel><ul className="mt-5 divide-y divide-light-line">{capabilities.map((item) => <li key={item} className="py-2.5 text-base text-muted-light">{item}</li>)}</ul></div></MotionSection><MotionSection className="grid gap-10 border-t border-light-line py-12 lg:grid-cols-2"><div><SectionLabel light>What this proves</SectionLabel><ul className="mt-6 space-y-3 text-base leading-relaxed"><li>Real client delivery in production.</li><li>Media-heavy brand website architecture.</li><li>Deployment workflow across Netlify and Cloudflare.</li><li>Client-facing business outcomes, not just builds.</li></ul></div><div><SectionLabel light>Live</SectionLabel><ul className="mt-6 space-y-3 text-base text-muted-light"><li><a href="https://steelmade.co.in/" target="_blank" rel="noreferrer" className="text-blue hover:underline">steelmade.co.in ↗</a></li><li><a href="https://github.com/element-bendr/steelmade-cloudiary" target="_blank" rel="noreferrer" className="text-blue hover:underline">Public implementation ↗</a></li></ul></div></MotionSection></div></section>
    <section className="bg-blue text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-14 sm:px-10 lg:flex-row lg:items-end lg:justify-between lg:px-16"><MotionItem><h2 className="display max-w-3xl text-[clamp(2.8rem,5vw,5rem)]">Need a production website that converts?</h2></MotionItem><MotionItem><ButtonLink href="/about#audit" light>Book an audit</ButtonLink></MotionItem></div></section>
  </PageShell>;
}
