import type { Metadata } from "next";
import { ButtonLink, PageShell, SectionLabel } from "@/components/site";
import { TrackVisit } from "@/components/TrackVisit";
import { MotionItem, MotionSection } from "@/components/motion";

export const metadata: Metadata = {
  title: "newsharness — News Intelligence Agent",
  description: "A Cloudflare-native intelligence system for scheduled collection, provider observability, story clustering, and traceable publishing.",
};

const chips = ["Cloudflare Agents SDK", "Durable Objects", "D1", "R2", "Workers AI", "Evals"];
const capabilities = ["Scheduled collection", "Provider normalization", "Story clustering", "Article extraction", "Draft generation", "Publishing workflows", "Traceable reporting"];

export default function NewsharnessPage() {
  return <PageShell><TrackVisit slug="newsharness" />
    <section className="bg-dark text-light"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:px-16 lg:py-16"><SectionLabel>Case study / 01</SectionLabel><h1 className="display mt-6 max-w-5xl text-[clamp(2.95rem,5.7vw,5.75rem)] leading-[.92]">Cloudflare Daily<br /><span className="text-cyan">News Intelligence Agent</span></h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-muted-dark">A Cloudflare-native intelligence system for scheduled collection, provider observability, story clustering, D1/R2 storage, article extraction, drafts, publishing, and traceable reporting.</p><div className="mt-7 grid gap-px border border-dark-line bg-dark-line sm:grid-cols-2 lg:grid-cols-4">{[["Type", "AI intelligence system"], ["Platform", "Cloudflare"], ["Status", "Built MVP / Cloudflare-native system"], ["Stack", "Agents SDK · Durable Objects · D1 · R2"]].map(([label, value]) => <div className="bg-dark p-4" key={label}><p className="font-mono text-[10px] uppercase tracking-[.12em] text-muted-dark">{label}</p><p className="mt-2 text-sm text-light">{value}</p></div>)}</div><div className="mt-7 flex flex-wrap gap-2">{chips.map((chip) => <span key={chip} className="border border-dark-line px-3 py-2 font-mono text-[11px] text-muted-dark">{chip}</span>)}</div></div></section>
    <section className="bg-light text-ink"><div className="mx-auto max-w-7xl px-6 py-12 sm:px-10 lg:px-16"><MotionSection className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><SectionLabel light>Overview</SectionLabel><p className="mt-6 text-2xl leading-tight">newsharness is a Cloudflare-native agent that discovers, curates, and delivers daily news intelligence.</p></div><p className="max-w-xl text-base leading-relaxed text-muted-light">It orchestrates end-to-end pipelines using Cloudflare primitives with observability and traceability at each step.</p></MotionSection><MotionSection className="mt-10 border-y border-light-line py-7"><SectionLabel light>System architecture</SectionLabel><div className="mt-5 grid gap-px overflow-hidden border border-light-line bg-light-line sm:grid-cols-3 lg:grid-cols-6">{["Sources", "Provider normalization", "Story clustering", "Extraction + enrichment", "Drafts + publishing", "D1 analytics + R2 artifacts"].map((item, i) => <div key={item} className="bg-light p-4"><span className="font-mono text-xs text-blue">0{i + 1}</span><p className="mt-5 text-sm leading-tight">{item}</p></div>)}</div></MotionSection><MotionSection className="grid gap-10 py-12 lg:grid-cols-2"><div><SectionLabel light>Problem</SectionLabel><p className="mt-6 text-2xl leading-tight">News is fragmented, noisy, and fast-moving. Manual aggregation and publishing do not scale.</p></div><div><SectionLabel light>What it does</SectionLabel><ul className="mt-5 divide-y divide-light-line">{capabilities.map((item) => <li key={item} className="py-2.5 text-base text-muted-light">{item}</li>)}</ul></div></MotionSection><MotionSection className="grid gap-10 border-t border-light-line py-12 lg:grid-cols-2"><div><SectionLabel light>What this proves</SectionLabel><ul className="mt-6 space-y-3 text-base leading-relaxed"><li>Cloudflare Agents can orchestrate practical content pipelines.</li><li>D1/R2/Durable Objects can support inspectable AI workflows.</li><li>AI-assisted reporting should be observable and traceable.</li><li>Separation of concerns improves reliability and maintainability.</li></ul></div><div><SectionLabel light>Next improvements</SectionLabel><ul className="mt-6 space-y-3 text-base text-muted-light"><li>Richer evals</li><li>Better personalization</li><li>Public Ask the Work integration</li><li>Stronger reviewer workflow</li><li>Source credibility scoring</li></ul></div></MotionSection></div></section>
    <section className="bg-blue text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-14 sm:px-10 lg:flex-row lg:items-end lg:justify-between lg:px-16"><MotionItem><h2 className="display max-w-3xl text-[clamp(2.8rem,5vw,5rem)]">Want to build something inspectable?</h2></MotionItem><MotionItem><ButtonLink href="/about" light>Book an audit</ButtonLink></MotionItem></div></section>
  </PageShell>;
}
