import type { Metadata } from "next";
import { ButtonLink, PageShell, SectionLabel } from "@/components/site";
import { MotionItem, MotionSection } from "@/components/motion";

export const metadata: Metadata = {
  title: "Mnemos — Governed AI Memory Prototype",
  description: "A governed AI memory system for reviewable knowledge ingestion from web, PDF, and paper sources.",
};

const chips = ["Next.js", "Node.js", "Postgres", "Playwright", "Docker Compose", "LLM adapters"];
const capabilities = ["Web / PDF / paper ingestion", "Patch protocol", "Audit logs", "Health checks", "Topic-based notes"];

export default function MnemosPage() {
  return <PageShell>
    <section className="bg-dark text-light"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:px-16 lg:py-16"><SectionLabel>Case study / 07</SectionLabel><h1 className="display mt-6 max-w-5xl text-[clamp(2.95rem,5.7vw,5.75rem)] leading-[.92]">Governed AI<br /><span className="text-cyan">Memory Prototype</span></h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-muted-dark">A governed AI memory system where knowledge ingestion from web, PDF, and paper sources gets reviewable structure instead of loose AI summaries.</p><div className="mt-7 grid gap-px border border-dark-line bg-dark-line sm:grid-cols-2 lg:grid-cols-4">{[["Type", "Knowledge system"], ["Platform", "Local prototype"], ["Status", "Governed AI memory prototype"], ["Stack", "Next.js · Postgres · Playwright · Docker"]].map(([label, value]) => <div className="bg-dark p-4" key={label}><p className="font-mono text-[10px] uppercase tracking-[.12em] text-muted-dark">{label}</p><p className="mt-2 text-sm text-light">{value}</p></div>)}</div><div className="mt-7 flex flex-wrap gap-2">{chips.map((chip) => <span key={chip} className="border border-dark-line px-3 py-2 font-mono text-[11px] text-muted-dark">{chip}</span>)}</div></div></section>
    <section className="bg-light text-ink"><div className="mx-auto max-w-7xl px-6 py-12 sm:px-10 lg:px-16"><MotionSection className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><SectionLabel light>Overview</SectionLabel><p className="mt-6 text-2xl leading-tight">Knowledge ingestion from the web, PDFs, and papers needs reviewable structure, not loose AI summaries.</p></div><p className="max-w-xl text-base leading-relaxed text-muted-light">Mnemos uses a Next.js UI, a Node.js control plane, and a Playwright executor with Postgres as source of truth and an LLM patch-review protocol for auditable updates.</p></MotionSection><MotionSection className="mt-10 border-y border-light-line py-7"><SectionLabel light>System architecture</SectionLabel><div className="mt-5 grid gap-px overflow-hidden border border-light-line bg-light-line sm:grid-cols-3 lg:grid-cols-6">{[["UI", "Next.js"], ["Control", "Node.js control plane"], ["Ingest", "Playwright executor"], ["Truth", "Postgres source of truth"], ["Review", "LLM patch protocol"], ["Ops", "Docker Compose + health checks"]].map(([step, tool], i) => <div key={step} className="bg-light p-4"><span className="font-mono text-xs text-blue">0{i + 1}</span><p className="mt-5 text-sm font-semibold leading-tight">{step}</p><p className="mt-1 text-xs leading-relaxed text-muted-light">{tool}</p></div>)}</div></MotionSection><MotionSection className="grid gap-10 py-12 lg:grid-cols-2"><div><SectionLabel light>Problem</SectionLabel><p className="mt-6 text-2xl leading-tight">AI summaries drift. Knowledge captured from sources needs structure, provenance, and review before it becomes memory.</p></div><div><SectionLabel light>What it does</SectionLabel><ul className="mt-5 divide-y divide-light-line">{capabilities.map((item) => <li key={item} className="py-2.5 text-base text-muted-light">{item}</li>)}</ul></div></MotionSection><MotionSection className="grid gap-10 border-t border-light-line py-12 lg:grid-cols-2"><div><SectionLabel light>What this proves</SectionLabel><ul className="mt-6 space-y-3 text-base leading-relaxed"><li>Governed AI memory design and auditability.</li><li>LLM patch-review architecture over direct writes.</li><li>Playwright-driven ingestion and Dockerized local AI systems.</li><li>Health-check thinking for local infrastructure.</li></ul></div><div><SectionLabel light>Note</SectionLabel><p className="mt-6 text-base text-muted-light">The repository is private. This public case study is sanitized; source and internal implementation details are not published.</p></div></MotionSection></div></section>
    <section className="bg-blue text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-14 sm:px-10 lg:flex-row lg:items-end lg:justify-between lg:px-16"><MotionItem><h2 className="display max-w-3xl text-[clamp(2.8rem,5vw,5rem)]">Want memory your team can trust?</h2></MotionItem><MotionItem><ButtonLink href="/about" light>Book an audit</ButtonLink></MotionItem></div></section>
  </PageShell>;
}
