import type { Metadata } from "next";
import { ButtonLink, PageShell, SectionLabel } from "@/components/site";
import { TrackVisit } from "@/components/TrackVisit";
import { MotionItem, MotionSection } from "@/components/motion";
import { CaseStudyMeta } from "@/components/CaseStudyMeta";
import { createMetadata } from "@/src/lib/seo";

export const metadata: Metadata = createMetadata({ path: "/work/kpdc-trifecta", title: "KPDC / Trifecta — Institutional Publishing System", description: "A multi-site institutional publishing system: three public static websites plus a private admin app with shared packages and staff workflows." });

const chips = ["Next.js", "Cloudflare Pages", "R2", "Monorepo", "Admin workflows", "Handover docs"];
const capabilities = ["Notices and updates", "PDF and gallery management", "Metadata management", "Staff publishing workflows", "Public site + private admin split"];

export default function KpdcTrifectaPage() {
  return <PageShell><TrackVisit slug="kpdc-trifecta" />
    <section className="bg-dark text-light"><div className="mx-auto max-w-7xl px-6 py-14 sm:px-10 lg:px-16 lg:py-16"><SectionLabel>Case study / 03</SectionLabel><h1 className="display mt-6 max-w-5xl text-[clamp(2.95rem,5.7vw,5.75rem)] leading-[.92]">Institutional<br /><span className="text-cyan">Publishing System</span></h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-muted-dark">Three public static websites plus one private admin app, with shared packages and staff publishing workflows.</p><CaseStudyMeta slug="kpdc-trifecta" /><div className="mt-7 grid gap-px border border-dark-line bg-dark-line sm:grid-cols-2 lg:grid-cols-4">{[["Type", "Publishing system"], ["Platform", "Cloudflare Pages"], ["Status", "Built institutional system"], ["Stack", "Next.js · R2 · Monorepo"]].map(([label, value]) => <div className="bg-dark p-4" key={label}><p className="font-mono text-[10px] uppercase tracking-[.12em] text-muted-dark">{label}</p><p className="mt-2 text-sm text-light">{value}</p></div>)}</div><div className="mt-7 flex flex-wrap gap-2">{chips.map((chip) => <span key={chip} className="border border-dark-line px-3 py-2 font-mono text-[11px] text-muted-dark">{chip}</span>)}</div></div></section>
    <section className="bg-light text-ink"><div className="mx-auto max-w-7xl px-6 py-12 sm:px-10 lg:px-16"><MotionSection className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><SectionLabel light>Overview</SectionLabel><p className="mt-6 text-2xl leading-tight">Institutions need to manage notices, PDFs, galleries, metadata, and public updates without depending on a developer for every small change.</p></div><p className="max-w-xl text-base leading-relaxed text-muted-light">This system gives staff controlled publishing workflows across public sites while keeping a private admin app for day-to-day content operations.</p></MotionSection><MotionSection className="mt-10 border-y border-light-line py-7"><SectionLabel light>System architecture</SectionLabel><div className="mt-5 grid gap-px overflow-hidden border border-light-line bg-light-line sm:grid-cols-3 lg:grid-cols-6">{[["Public sites", "3 static websites"], ["Admin app", "Private staff control"], ["Shared packages", "UI · config · content · storage · validation"], ["Storage", "R2"], ["Deployment", "Cloudflare Pages"], ["Handover", "Docs + build/QA commands"]].map(([step, tool], i) => <div key={step} className="bg-light p-4"><span className="font-mono text-xs text-blue">0{i + 1}</span><p className="mt-5 text-sm font-semibold leading-tight">{step}</p><p className="mt-1 text-xs leading-relaxed text-muted-light">{tool}</p></div>)}</div></MotionSection><MotionSection className="grid gap-10 py-12 lg:grid-cols-2"><div><SectionLabel light>Problem</SectionLabel><p className="mt-6 text-2xl leading-tight">Every content update was a developer task, and the institutions had no way to manage their own public presence.</p></div><div><SectionLabel light>What it does</SectionLabel><ul className="mt-5 divide-y divide-light-line">{capabilities.map((item) => <li key={item} className="py-2.5 text-base text-muted-light">{item}</li>)}</ul></div></MotionSection><MotionSection className="grid gap-10 border-t border-light-line py-12 lg:grid-cols-2"><div><SectionLabel light>What this proves</SectionLabel><ul className="mt-6 space-y-3 text-base leading-relaxed"><li>Business and admin system delivery.</li><li>Multi-site monorepo architecture.</li><li>Staff publishing workflows in production.</li><li>Cloudflare deployment planning, production readiness, and handover discipline.</li></ul></div><div><SectionLabel light>Live sites</SectionLabel><ul className="mt-6 space-y-3 text-base text-muted-light"><li><a href="https://www.kpcollege.in/" target="_blank" rel="noreferrer" className="text-blue hover:underline">Kalyani Patil Degree College ↗</a></li><li><a href="https://kalyanipatillawcollege.in/" target="_blank" rel="noreferrer" className="text-blue hover:underline">Kalyani Patil Law College ↗</a></li></ul></div></MotionSection></div></section>
    <section className="bg-blue text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-14 sm:px-10 lg:flex-row lg:items-end lg:justify-between lg:px-16"><MotionItem><h2 className="display max-w-3xl text-[clamp(2.8rem,5vw,5rem)]">Need a publishing system your team can run?</h2></MotionItem><MotionItem><ButtonLink href="/about#audit" light>Book an audit</ButtonLink></MotionItem></div></section>
  </PageShell>;
}
